language: go
go:
  - 1.2.2
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
before_install:
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/cloudfoundry"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../cloudfoundry/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi
script:  bin/test --compilers=2
branches:
  only:
  - master
