language: go
go:
  - 1.2.2
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
script:  bin/test --compilers=2

